# Generated by Django 2.1.1 on 2018-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_remove_user_master_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='Institute_Code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
