# Generated by Django 2.1.1 on 2018-09-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
