# Generated by Django 2.1.1 on 2018-09-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_auto_20180916_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Department')),
            ],
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='min_passing_marks',
            new_name='min_passing',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Subject_name',
            new_name='subject_code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Total_Marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='institute',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='total_marks',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
    ]
