# Generated by Django 2.1.1 on 2018-09-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_auto_20180916_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Contact_no', models.IntegerField(max_length=10)),
                ('parent_code', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
