# Generated by Django 2.1.1 on 2018-09-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='Contact_no',
            field=models.IntegerField(),
        ),
    ]
