# Generated by Django 2.1.1 on 2018-09-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0009_auto_20180916_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Roll_no', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Department')),
            ],
        ),
        migrations.AlterField(
            model_name='parent',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.Parent'),
        ),
    ]
