# Generated by Django 2.1.1 on 2018-09-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0010_auto_20180916_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='Contact_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_code',
            field=models.CharField(max_length=200),
        ),
    ]
