# Generated by Django 2.1.1 on 2018-09-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0011_auto_20180916_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
